import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { useAppSelector } from '../store/hooks'
import { selectUser } from '@github-profiles/store/slices/user'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const user = useAppSelector(selectUser)

  return (
    <div className={styles.container}>
      <Head>
        <title>Github Profiles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Github Profiles {user?.name && `, ${user.name}`}
        </h1>

        {user?.login ? (
          <a href={`/users/${user.login}`}>Go to my page</a>
        ) : (
          <a href={'/users/mtsdalmolin'}>Go to Matheus{"'"} page</a>
        )}
      </main>
    </div>
  )
}

export default Home
